version: '3.9'

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lista_telefonica
      MYSQL_USER: app_user
      MYSQL_PASSWORD: senha123
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uapp_user", "-psenha123" ]
      interval: 10s
      retries: 5
      timeout: 5s

  backend:
    build: ./backend
    expose:
      - "8080" # Disponível só dentro da rede Docker, não é publicado para fora
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_BANCO: lista_telefonica
      DB_USUARIO: app_user
      DB_SENHA: senha123
      JWT_SECRETS: xjS7od3KkilSGkGmyxNUFyuf6+SgqZKJeEmmscs4DHmfzdDo+oLxYQiVWUGaZTWS
      JWT_ASSINATURA: lista_telefonica_cjs
    depends_on:
      - mysql
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      retries: 5
      timeout: 5s

  frontend:
    build: ./frontend
    expose:
      - "80"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/" ]
      interval: 10s
      retries: 5
      timeout: 5s

  nginx:
    image: nginx:latest
    ports:
      - "81:80" # O usuário acessa o Nginx pela porta 81
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

volumes:
  mysql_data:


networks:
  app-network:
    driver: bridge
