version: '3.9'

services:
  mysql:
    image: mysql:8
    container_name: mysql_lista_telefonica
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lista_telefonica
      MYSQL_USER: app_user
      MYSQL_PASSWORD: senha123
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uapp_user", "-psenha123"]
      interval: 10s
      timeout: 5s
      retries: 5

  backendlistatelefonica:
    build: ./backend
    container_name: backend_lista_telefonica
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_BANCO: lista_telefonica
      DB_USUARIO: app_user
      DB_SENHA: senha123
      JWT_SECRETS: xjS7od3KkilSGkGmyxNUFyuf6+SgqZKJeEmmscs4DHmfzdDo+oLxYQiVWUGaZTWS
      JWT_ASSINATURA: lista_telefonica_cjs
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network
    # Não expomos porta para o host. Frontend acessa internamente via Docker.

  frontend:
    build: ./frontend
    container_name: frontend_lista_telefonica
    ports:
      - "8081:5500"  # Acessível no host em http://localhost:8081
    networks:
      - app-network
    depends_on:
      - backendListaTelefonica
