spring.application.name=lista_telefonica_cjs

# Configuração de DataSource
spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_BANCO}
spring.datasource.username=${DB_USUARIO}
spring.datasource.password=${DB_SENHA}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none

#Configuração do Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.clean-disabled=true

# Nunca exibir stacktrace no JSON de erro
server.error.include-stacktrace=never

#Token
api.security.token.secret = ${JWT_SECRETS}
api.security.token.issuer= ${JWT_ASSINATURA}